<?php if ($this->pageCount): ?>
	<div class="paginationControl">
	<!– Previous page link –>
	<?php if (isset($this->previous)): ?>
	<a href="<?= $this->url(array('page' => $this->previous)); ?>">
	&lt; <?php echo $this->translate('Previous')?>
	</a> |
	<?php else: ?>
	<span class=”disabled”>&lt; <?php echo $this->translate('Previous')?></span> |
	<?php endif; ?>

	<!– Numbered page links –>
	<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
	<a href="<?= $this->url(array('page' => $page)); ?>">
	<?= $page; ?>
	</a> |
	<?php else: ?>
	<?= $page; ?> |
	<?php endif; ?>
	<?php endforeach; ?>

	<!– Next page link –>
	<?php if (isset($this->next)): ?>
	<a href="<?= $this->url(array('page' => $this->next)); ?>">
	<?php echo $this->translate('Next')?> &gt;
	</a>
	<?php else: ?>
	<span class="disabled"><?php echo $this->translate('Next')?> &gt;</span>
	<?php endif; ?>
	</div>
	<?php endif; ?>
	
	<?php echo $this->translate('Showing '); echo $this->current; echo $this->translate(' out of '); echo $this-> pageCount; ?>