<?php foreach ($this->postsPaginator as $post) { ?>
<div class="post">
	<h1><a href="<?=$this->url(array('controller' => 'posts', 'action' => 'view', 'id' => $post->id))?>"><?=$post->title?></a></h1>(<?=$post->commentsCount?> comments)(<a href="<?=$this->url(array('controller' => 'posts', 'action' => 'delete', 'id' => $post->id))?>">Delete</a>)|(<a href="<?=$this->url(array('controller' => 'posts', 'action' => 'edit', 'id' => $post->id))?>">Edit</a>)
	<p><?=$post->text?></p>
</div>
<hr>
<?  } ?>
<?=$this->paginationControl($this->postsPaginator)?>